module.exports = {
  darkMode: 'class',
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
    "./app/**/*.{js,jsx,ts,tsx,css}"
  ],
  theme: {
    extend: {
      colors: {
        border: 'hsl(var(--border))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        card: 'hsl(var(--card))',
        'card-foreground': 'hsl(var(--card-foreground))',
        popover: 'hsl(var(--popover))',
        'popover-foreground': 'hsl(var(--popover-foreground))',
        primary: 'hsl(var(--primary))',
        'primary-foreground': 'hsl(var(--primary-foreground))',
        secondary: 'hsl(var(--secondary))',
        'secondary-foreground': 'hsl(var(--secondary-foreground))',
        muted: 'hsl(var(--muted))',
        'muted-foreground': 'hsl(var(--muted-foreground))',
        accent: 'hsl(var(--accent))',
        'accent-foreground': 'hsl(var(--accent-foreground))',
        destructive: 'hsl(var(--destructive))',
        'destructive-foreground': 'hsl(var(--destructive-foreground))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        olive: {
          50: '#f6f8f4',
          100: '#e6f4d7',
          200: '#cfe3b4',
          300: '#b5c99a',
          400: '#9bb17d',
          500: '#7d995f',
          600: '#5e7a45',
          700: '#42552e',
          800: '#2a331a',
          900: '#181d0d',
        },
        earth: {
          50: '#fdfaf6',
          100: '#f7ecd9',
          200: '#e9d3b0',
          300: '#d6b77e',
          400: '#bfa05a',
          500: '#a1843d',
          600: '#7a642b',
          700: '#55451b',
          800: '#32280e',
          900: '#1a1405',
        },
        futuristic: {
          50: '#f5f7fa',
          100: '#c3cbe4',
          200: '#8b9fd1',
          300: '#5a73be',
          400: '#2a47ab',
          500: '#1a2a5c',
          600: '#141f44',
          700: '#0e142c',
          800: '#090b16',
          900: '#04050a',
        },
        neon: {
          100: '#e0fffc',
          200: '#7afcff',
          300: '#32ffd2',
          400: '#18e6c1',
          500: '#00bfae',
        },
      },
      fontFamily: {
        display: ['Montserrat', 'ui-sans-serif', 'system-ui'],
        body: ['Inter', 'ui-sans-serif', 'system-ui'],
      },
    },
  },
  plugins: [],
};
